from .loaders import NODE_CLASS_MAPPINGS as LOADER_NODES, NODE_DISPLAY_NAME_MAPPINGS as LOADER_NAMES
from .samplers import NODE_CLASS_MAPPINGS as SAMPLER_NODES, NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_NAMES
from .vae import NODE_CLASS_MAPPINGS as VAE_NODES, NODE_DISPLAY_NAME_MAPPINGS as VAE_NAMES
from .status import NODE_CLASS_MAPPINGS as STATUS_NODES, NODE_DISPLAY_NAME_MAPPINGS as STATUS_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_NODES)
NODE_CLASS_MAPPINGS.update(SAMPLER_NODES)
NODE_CLASS_MAPPINGS.update(VAE_NODES)
NODE_CLASS_MAPPINGS.update(STATUS_NODES)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(SAMPLER_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(VAE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(STATUS_NAMES)
